name: hive_discovery
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive:
    ^2.2.3
    # git:
    #   url: https://github.com/Flutterando/modular.git
    #   path: flutter_modular
    #   ref: modular_6
  dio: ^4.0.6
  flutter_modular: ^5.0.3
  path_provider: ^2.0.11
  asuka: ^2.0.1+3
  infinite_scroll_pagination: ^3.2.0
  faker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
